### ISSUE TITLE
讯飞星火大模型连接后一段时间，就会被服务器拒绝。重启服务后，又可以用一段时间

### ISSUE THREAD

**Issue by JiangWatson** [tian-minghui/openai-style-api#14]
<img width="837" alt="image" src="https://github.com/tian-minghui/openai-style-api/assets/15996184/90b21989-f7c9-4877-967b-6e5eef729799">
这是什么原因？

**Comment by JiangWatson** [comment]
wss中时间验证信息，在初始化后就不在更新引起的

**Comment by tian-minghui** [comment]
感谢，后边修复下

**Comment by w568w** [comment]
为什么要 close？问题根本还没解决吧…
