### ISSUE TITLE
新版本openai库无法请求

### ISSUE THREAD

**Issue by HuaShanWoZuiShuai** [tian-minghui/openai-style-api#15]
使用openai==0.28可以正常使用，curl也能通，但是换用新版openai配置后，无法接收请求

**Comment by tian-minghui** [comment]
> 使用openai==0.28可以正常使用，curl也能通，但是换用新版openai配置后，无法接收请求

可以贴一下报错信息么

**Comment by tian-minghui** [comment]
openai>=1.0.0使用以下方式调用
    
    import os
    from openai import OpenAI

    client = OpenAI(
        # This is the default and can be omitted
        api_key='kimi-GxqT3BlbkFJj',
        base_url = 'http://localhost:8090/v1'
    )

    chat_completion = client.chat.completions.create(
        messages=[
            {
                "role": "user",
                "content": "Say this is a test",
            }
        ],
        model="gpt-3.5-turbo",
    )

    print(chat_completion.choices[0].message.content)

**Comment by tian-minghui** [comment]
closed
