### ISSUE TITLE
请问可以提供Docker 或者 安装环境/版本吗？ 

### ISSUE THREAD

**Issue by Bossjava** [tian-minghui/openai-style-api#5]
人都装麻了，一会aiohttp装不上，一会

ERROR: Failed building wheel for multidict
Failed to build multidict
ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects

python3.10

谢谢

**Comment by tian-minghui** [comment]
有docker版本呀，  目录下执行  docker compose up -d
